{% set version = "1.1-8" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-simpleboot
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/simpleboot_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/simpleboot/simpleboot_{{ version }}.tar.gz
  sha256: dd094737f679457282a121e3391fc89aca6db4c1822066a3e35f1f7aa7d4f8a2

build:
  number: 2
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-boot
  run:
    - r-base
    - r-boot

test:
  commands:
    - $R -e "library('simpleboot')"           # [not win]
    - "\"%R%\" -e \"library('simpleboot')\""  # [win]

about:
  home: https://github.com/rdpeng/simpleboot
  license: GPL-2.0-or-later
  summary: Simple bootstrap routines.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r
    - philip-khor

# Package: simpleboot
# Version: 1.1-7
# Depends: R (>= 2.14.0)
# Imports: boot, stats, graphics
# Title: Simple Bootstrap Routines
# Author: Roger D. Peng <rpeng@jhsph.edu>
# Maintainer: Roger D. Peng <rpeng@jhsph.edu>
# Description: Simple bootstrap routines.
# License: GPL (>= 2)
# URL: https://github.com/rdpeng/simpleboot
# NeedsCompilation: no
# Packaged: 2019-02-20 16:58:57 UTC; rdpeng
# Repository: CRAN
# Date/Publication: 2019-02-20 22:00:03 UTC
