appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: L4kkZE2s4xlzPbiYlrtTq0OHiALbwkXz1p6y7AxvPfdotTCELw7ACaM1G7S5DwiQBGcb5FDnskHpVwzzNcQPbF/MBLT8ATV3t+teZPBdGKKXzVsNbPNuQ+0Ocw8bDxOgHWI1HkjRSumo2dosN+yZAPz4JvtZYZQYeub6uGpt8LyXjGCmWghil7pnNF0eyrsR5bxb1j1qxSR/xGveh6sz6SRT1pnqu89eZcsuXam6VZBnbPg6jmErbXR8bfSmpsePbXy51WaKqhLP5feAh0M4HMdVuZwVkOrYVzdr2wk5qt+EoN6E5MZk8vFAmGYbbflhTJTs+uwXeoR6KrouZrgfTzGSfXSY9dqTInAwvxTopXlmGR1hvb4ENfN3mJD1zI8/+OktKbr97/u0F2/sHhDDx6WiHB9/+QHPBj7Z0Sl5fbEQuiKUDfw7yttM1UFU1HL/AXxAhS+ZfIHbMRcJUh8N5wtLOsc+RyUXFcNsy+3qjtQMTFAp5lkFmCJNTZRWVxN7uaHyaT3z0t5vDDJlHSERLIUcou9oXJyi3RG8ermAGu1gzGMFjuSjYvyeltCF9pPcTKGroHoDhSrReSmgTo5YWdmIO5huBQ3b4gyRoxEtfO4f3L0XL7KAiRnkRBmmxzZMJe/HcHY0C3io0PnGtbWkW/Gvua28oHrr6f/zsekAla8=}
